In [12]:
import pandas as pd
import numpy as np
import re

In [2]:
df = pd.read_csv('free_shop.csv', sep=';')
df.head()

,longitude,latitude,shopDescription,sunusng,ipom,weiwei
0,-1.51815,43.49507,[Orange] 64 Anglet (Avenue Belle Marion),5,7,10
1,-1.42988,46.66976,[Orange] 85 La Roche-sur-Yon (15 Rue Georges C...,3,3,2
2,-1.43024,46.69141,[Orange] 85 La Roche-sur-Yon (CC Les Flaneries),5,9,5
3,-1.54907,47.16152,"[Orange] 44 Rezé (10 rond-point Corbinerie ,CC...",8,4,8
4,-1.46916,47.18722,[Orange] 44 Basse-Goulaine (CC Leclerc Pôle Sud),0,4,5

In [3]:
df.columns

Index(['longitude', 'latitude', 'shopDescription', 'sunusng', 'ipom',
       'weiwei'],
      dtype='object')

In [4]:
df.dtypes

longitude          float64
latitude           float64
shopDescription     object
sunusng              int64
ipom                 int64
weiwei               int64
dtype: object

In [5]:
df.rename(columns={
    'sunusng': 'samsung', 
    'ipom': 'iphone',
    'weiwei': 'huawei',                   
                   }, inplace=True)

In [6]:
df.columns

Index(['longitude', 'latitude', 'shopDescription', 'samsung', 'iphone',
       'huawei'],
      dtype='object')

In [7]:
df['shopDescription']

0               [Orange] 64 Anglet (Avenue Belle Marion)
1      [Orange] 85 La Roche-sur-Yon (15 Rue Georges C...
2        [Orange] 85 La Roche-sur-Yon (CC Les Flaneries)
3      [Orange] 44 Rezé (10 rond-point Corbinerie ,CC...
4       [Orange] 44 Basse-Goulaine (CC Leclerc Pôle Sud)
                             ...
221                [Orange] 35 Rennes (22 Rue Tronjolly)
222    [Orange] 35 Rennes (CC Intermarché Long-Champs...
223              [Orange] 35 Rennes (CC Leclerc Cleunay)
224       [Orange] 35 Fougères (6 Boulevard Jean Jaurès)
225           [Orange] 56 Vannes (23 Rue Joseph le Brix)
Name: shopDescription, Length: 226, dtype: object

In [8]:
df['departement'] = df['shopDescription'].str.extract(r'\[Orange\]\s+(\d+)')
df['departement'] = df['departement'].astype('Int64')
df['departement']

0      64
1      85
2      85
3      44
4      44
       ..
221    35
222    35
223    35
224    35
225    56
Name: departement, Length: 226, dtype: Int64

In [11]:
df['departement'].isna().value_counts()

departement
False    225
True       1
Name: count, dtype: int64

In [42]:
# Extraction de la ville
df['ville'] = df['shopDescription'].str.extract(r'\[Orange\]\s+\d+\s+([^\(]+)')
df['ville'] = df['ville'].str.strip()
df['ville']

0                Anglet
1      La Roche-sur-Yon
2      La Roche-sur-Yon
3                  Rezé
4        Basse-Goulaine
             ...
221              Rennes
222              Rennes
223              Rennes
224            Fougères
225              Vannes
Name: ville, Length: 226, dtype: object

In [43]:
# Extraction de l'adresse
df['adresse'] = df['shopDescription'].str.extract(r'\(([^\)]+)\)')
df['adresse'] = df['adresse'].str.strip()
df['adresse']

0                                    Avenue Belle Marion
1                              15 Rue Georges Clémenceau
2                                       CC Les Flaneries
3                    10 rond-point Corbinerie ,CC Océane
4                                    CC Leclerc Pôle Sud
                             ...
221                                     22 Rue Tronjolly
222    CC Intermarché Long-Champs ,Allée Morvan Lebesque
223                                   CC Leclerc Cleunay
224                              6 Boulevard Jean Jaurès
225                                23 Rue Joseph le Brix
Name: adresse, Length: 226, dtype: object

In [44]:
# Vous pouvez aussi nettoyer la colonne originale
df['shopDescription_clean'] = df['shopDescription'].str.replace(r'^\[Orange\]\s+\d+\s+', '', regex=True)
df['shopDescription_clean']

0                           Anglet (Avenue Belle Marion)
1           La Roche-sur-Yon (15 Rue Georges Clémenceau)
2                    La Roche-sur-Yon (CC Les Flaneries)
3             Rezé (10 rond-point Corbinerie ,CC Océane)
4                   Basse-Goulaine (CC Leclerc Pôle Sud)
                             ...
221                            Rennes (22 Rue Tronjolly)
222    Rennes (CC Intermarché Long-Champs ,Allée Morv...
223                          Rennes (CC Leclerc Cleunay)
224                   Fougères (6 Boulevard Jean Jaurès)
225                       Vannes (23 Rue Joseph le Brix)
Name: shopDescription_clean, Length: 226, dtype: object

In [45]:
df.head()

,longitude,latitude,shopDescription,samsung,iphone,huawei,departement,ville,adresse,shopDescription_clean
0,-1.51815,43.49507,[Orange] 64 Anglet (Avenue Belle Marion),5,7,10,64,Anglet,Avenue Belle Marion,Anglet (Avenue Belle Marion)
1,-1.42988,46.66976,[Orange] 85 La Roche-sur-Yon (15 Rue Georges C...,3,3,2,85,La Roche-sur-Yon,15 Rue Georges Clémenceau,La Roche-sur-Yon (15 Rue Georges Clémenceau)
2,-1.43024,46.69141,[Orange] 85 La Roche-sur-Yon (CC Les Flaneries),5,9,5,85,La Roche-sur-Yon,CC Les Flaneries,La Roche-sur-Yon (CC Les Flaneries)
3,-1.54907,47.16152,"[Orange] 44 Rezé (10 rond-point Corbinerie ,CC...",8,4,8,44,Rezé,"10 rond-point Corbinerie ,CC Océane","Rezé (10 rond-point Corbinerie ,CC Océane)"
4,-1.46916,47.18722,[Orange] 44 Basse-Goulaine (CC Leclerc Pôle Sud),0,4,5,44,Basse-Goulaine,CC Leclerc Pôle Sud,Basse-Goulaine (CC Leclerc Pôle Sud)

In [46]:
df2 = df.copy()
df2 = df2.drop(columns=['shopDescription', 'shopDescription_clean'])
df2.head()

,longitude,latitude,samsung,iphone,huawei,departement,ville,adresse
0,-1.51815,43.49507,5,7,10,64,Anglet,Avenue Belle Marion
1,-1.42988,46.66976,3,3,2,85,La Roche-sur-Yon,15 Rue Georges Clémenceau
2,-1.43024,46.69141,5,9,5,85,La Roche-sur-Yon,CC Les Flaneries
3,-1.54907,47.16152,8,4,8,44,Rezé,"10 rond-point Corbinerie ,CC Océane"
4,-1.46916,47.18722,0,4,5,44,Basse-Goulaine,CC Leclerc Pôle Sud

In [47]:
df2.isna().sum()

longitude      0
latitude       0
samsung        0
iphone         0
huawei         0
departement    9
ville          9
adresse        0
dtype: int64

In [50]:
# Pour voir les lignes complètes où le département est null
df2[df2['departement'].isna()]

,longitude,latitude,samsung,iphone,huawei,departement,ville,adresse
14,-2.21331,47.27441,7,0,3,<NA>,NaN,2 Avenue de la République
27,-1.05382,43.70975,7,5,7,<NA>,NaN,38 Rue des Carmes
39,-0.80670,46.46630,7,0,7,<NA>,NaN,12 Rue Georges Clémenceau
42,-1.01455,46.87096,5,4,5,<NA>,NaN,17 Rue de l’Eglise
74,-2.72855,48.49653,5,10,6,<NA>,NaN,1 Rue Jules Verne
81,-1.67796,48.10986,2,5,10,<NA>,NaN,Place de la République
87,-0.62209,48.30347,2,1,10,<NA>,NaN,40 Place Gambetta
89,-1.99573,48.62401,9,5,2,<NA>,NaN,CC La Madeleine
218,-2.75994,48.51365,6,5,2,<NA>,NaN,16 Rue Saint-Guillaume